config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/help', 			to: 'static_pages#help'			#estas configuraciones de routes (controller#action) 
  get '/about', 		to: 'static_pages#about'		#permite tener a disposicion una ruta llamada _path o _url
  get '/contact',		to: 'static_pages#contact'
  get '/signup',		to: 'users#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase } #self refers to teh corrent user
	validates :name, 	presence: true, length: { maximum: 50 }
	#VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i #constante por iniciar con upercase 'VALID...'
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }
	has_secure_password #goes with 'password_digest' upon users model (on table as a row)
	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
  	render html: "Hola mundo!!!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper 
#el modulo puede ser utilizado para empaquetar aquellas funciones de ayuda, 
#que pueden ser mezclados dentro de las clases de ruby usando 'include'. 
#Este helper se incluye automaticamente en todas las views del app
	
	#Returns the full title on a per-page basis
	def full_title(page_title = '')							#Method def, optional argument
		base_title = "SmartFarm"							#variable assigment
		if page_title.empty?								#boolean test or control flow
			base_title										#implicit return
		else
			page_title + " | " + base_title					#else implicit return, String concatenation
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Un desarrollo de <a href="#">SonfInc 2018</a>. Todos los derechos reservados.
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
	<div class="container-fluid">
		<div class="navbar-header">
		  <%= link_to image_tag("icons/navBarLogo.png", alt: "Logo SmartFarm"), root_path, id: "logo" %>
		</div>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<li><%= link_to "Log in", '#' %></li>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>    
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<div class="container">
  		<%= yield %>
  		<%= render 'layouts/footer' %>
  	</div>    
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
	Esta es una aplicacion web es una desarrollo de <a href="#">Yeiner Carvajal Quina</a> y <a href="#">SoftInc</a>. 
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
	Para mayor informacion sobre este desarrollo, envienos sus comentarios al correo electronico <a href="#">contact@smartfarm.com</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
	Para solicitar ayuda relacionada con esta aplicacion, por favor comuniquese con el <a href="#">administrador</a>.
	<br><br>
	Saludos!
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	
	<h1>Bienvenido a SmartFarm</h1>
	
	<p>
		Aqui pordras organizar el trabajo de tu finca. El futuro se forja aqui y ahora, queremos verte como un gran empresario.
	</p>
	<%= link_to "Registrate!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("icons/logoSmartFarm.png", alt: "Logo SmartFarm"), '#' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Registrarse</h1>
<p>Aqui se configurara la pagina de registro para nuevos usuarios</p>